FROM navikt/python-fasttext:0.8.22

COPY ca-bundle.crt /usr/local/share/ca-certificates/ca-bundle.crt

COPY app /app

ADD https://storage.googleapis.com/ai-lab-modeller/nace_model.bin /app/static/model.bin

WORKDIR /app

RUN pip install --cert /usr/local/share/ca-certificates/ca-bundle.crt -r requirements.txt

CMD ["python", "app.py"]