version: "3.5"

services:
  api:
    image: offentlig-ai/nace-predictor-api:latest
    ports:
      - 8081:8081

  test-client:
    image: offentlig-ai/nace-predictor-test-client:latest
    ports:
      - 8080:3000
    environment:
      - REACT_APP_API_URL=http://localhost:8081
    depends_on:
      - api
