FROM navikt/python-fasttext:0.8.22

COPY ca-bundle.crt /usr/local/share/ca-certificates/ca-bundle.crt
COPY aws-credentials /root/.aws/credentials
COPY app /app

WORKDIR /app

RUN pip install --proxy http://webproxy-utvikler.nav.no:8088 --cert /usr/local/share/ca-certificates/ca-bundle.crt -r requirements.txt

RUN aws --endpoint-url https://s3.nais.preprod.local --no-verify-ssl s3api get-object --bucket ai-lab --key ai-lab-nace-poc/nace_model.bin /app/static/model.bin

CMD ["python", "app.py"]
